channels:
- conda-forge
dependencies:
- python=3.12.10
- pip<=25.2
- pip:
  - mlflow==3.4.0
  - cloudpickle==3.1.1
  - numpy==1.26.2
  - psutil==7.0.0
  - scikit-learn==1.4.1.post1
  - scipy==1.15.2
name: mlflow-env
